server:
  port: 8081

spring:
  application:
    name: user-service

  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msa_user_db?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "${MYSQL_ROOT_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # 게이트웨이(BFF)가 전송해 준 JWT 토큰 서명을 리소스 서버 관점에서 로컬 검증 처리
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/msa-shop
          jwk-set-uri: http://localhost:8080/realms/msa-shop/protocol/openid-connect/certs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  server-url: http://localhost:8080
  realm: master
  client-id: admin-cli
  username: admin
  password: 1234
  target-realm: msa-shop